### ISSUE TITLE
Missing mime types for some headers

### ISSUE THREAD

**Issue by msdinit** [cdgriffith/puremagic#14]
Some of the headers in magic_data lack mime-type, for example:
https://github.com/cdgriffith/puremagic/blob/master/puremagic/magic_data.json#L69
This causes `from_string(str, mime=True)` to return empty string instead of the mime-type in some cases, eg JPEG image.

Is there a specific reason for this, or is the dataset just incomplete?

**Comment by cdgriffith** [comment]
No specific reason other than the data sets this was pulled from was incomplete. It's been a few years since an update though, so I will keep this open so I can try and find more sources and new files to add, and hopefully fill in missing mime types in the process. 

Thanks for the reminder!

**Comment by cdgriffith** [comment]
Have gone through and added various mime types that I could find that were missing in the upcoming [1.8](https://github.com/cdgriffith/puremagic/pull/25). Thanks!
