### ISSUE TITLE
Is it possible to use filehandles / bytestream?

### ISSUE THREAD

**Issue by MT-Cash** [cdgriffith/puremagic#36]
I would love to do something like this:

```
import puremagic

with open(file_path, "rb") as fh:
    ext = puremagic.from_file_handler(fh)
```

Especially the bytestream support might be nice in case the file is not / cannot / should not be stored on the disk (e.g. AWS Lambda)

**Comment by cdgriffith** [comment]
Added quick example to readme with latest release. Thanks for pointing out the omission!
