### ISSUE TITLE
missing mime type for webp

### ISSUE THREAD

**Issue by phith0n** [cdgriffith/puremagic#38]
For example, this is a webp image, download it to `test.webp`:

![](https://file-examples-com.github.io/uploads/2020/03/file_example_WEBP_50kB.webp)

This is the difference between **puremagic** and **magic**:

```python
In [22]: import puremagic

In [23]: puremagic.from_file("test.webp", mime=True)
Out[23]: ''

In [24]: import magic

In [25]: magic.from_file("test.webp", mime=True)
Out[25]: 'image/webp'
```

It is seems that mime is missing, but if I remove the `mime=True`. I can get the webp extension:

```
In [26]: puremagic.from_file("test.webp")
Out[26]: '.webp'
```

**Comment by cdgriffith** [comment]
thanks for the heads up, added in https://github.com/cdgriffith/puremagic/releases/tag/1.12
