### ISSUE TITLE
.epub listed as "INI Config file" in magic_data.json

### ISSUE THREAD

**Issue by tritium21** [cdgriffith/puremagic#45]
A file with an .epub extension is extremely likely to be the zip+xml+html based, and extremely popular, e-book format rather than any form of INI configuration file.  I cannot find any reference to .epub being a configuration file name for any system with a cursory search.

As it is listed directly after .ini in the data file, it was likely a copy/paste error.

The line should probably read as:
```
        ["", 0, ".epub", "application/epub+zip", "electronic book document"]
```

**Comment by cdgriffith** [comment]
Removed that and added a better detection for epub as well! https://github.com/cdgriffith/puremagic/releases/tag/1.20
