### ISSUE TITLE
JPEG XS Two mime types

### ISSUE THREAD

**Issue by NebularNerd** [cdgriffith/puremagic#52]
I was having a look around the various JPEG X* flavours and came across [https://en.wikipedia.org/wiki/JPEG_XS](https://en.wikipedia.org/wiki/JPEG_XS) which is both a still image and video codec. 

Just to be awkward they use the same fingerprint `0xFF10 FF50` for both image and video but then give it two mime types `image/jxsc` and `video/jxsv`.

What would be the best approach to handle this? Two entries in the .json one for each type? I'm not sure of other formats that would do this but I reckon they are out there.

**Comment by cdgriffith** [comment]
There might be more information inside the file itself, I sadly don't have an ISO memebership so can't check the full spec file. 

I would personally default to just the image. As even most viewers for JPEG XL / AVIF / HEIF only support the still image aspect of them.

**Comment by NebularNerd** [comment]
I'll try and find some test files and see if there is an additional fingerprint we could use. Hopefully there will be a nice little byte or two that gives away what inside. 🙂

**Comment by NebularNerd** [comment]
Mmmm.... Looking at a .jxs image (after compiling the reference software) it seems the images at least have a fairly long fingerprint with a few changes depending on the profile used, then at byte 102 we get `0x49 53 4F 2D 32 31 31 32 32 2D 35 2D 32 2E 30 2E 32 2D 45 44 32` which is `ISO-21122-5-2.0.2-ED2`

**Comment by cdgriffith** [comment]
Added in 1.22 https://github.com/cdgriffith/puremagic/releases/tag/1.22
