### ISSUE TITLE
Multi-part checks with negative offset for second match

### ISSUE THREAD

**Issue by NebularNerd** [cdgriffith/puremagic#57]
I'm just going through some various files for some formats, in some cases I could increase the confidence as the file has both a solid position for a header, but also a solid position for a footer. Would it be possible to have the multi-part use a negative byte count to match from?

This would be handy as in one case I have a file that is clashing with another match at 0.8, adding the footer as an additional match should push past this to give a solid first match. I believe this would help with things like #37 .svg matching confidence as well.

Example entry for multi-part-headers:

```
"4352454D" : [
    ["444f4e4500000000", -8, ".ctm", "", "CreamTracker module"]			
]
```

**Comment by cdgriffith** [comment]
Added in https://github.com/cdgriffith/puremagic/releases/tag/1.22 thanks!
