### ISSUE TITLE
For Python 3.13: A drop-in replacement for `imghdr.what()`

### ISSUE THREAD

**Issue by cclauss** [cdgriffith/puremagic#72]
Given the discussion in #67 about `imghdr` being removed from the Python Standard Library, it might be quite helpful to have a ___drop-in replacement___ for [`imghdr.what()`](https://docs.python.org/3/library/imghdr.html#imghdr.what).  It would provide a smooth transition to Py3.13 if developers could confidently replace all instances of `imghdr.what()` with `puremagic.what()` -- same args, same results.
* https://docs.python.org/3.12/library/imghdr.html
* #67
* #68

**Comment by NebularNerd** [comment]
Oddly I was thinking of this the other day, I've not used `imghdr` does it literally just return an extension?

**Comment by cclauss** [comment]
% `python3.12 -c"import imghdr ; print(imghdr.what(None, b'\xff\xd8\xff\xdb'))"`
```
<string>:1: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
jpeg
```

**Comment by NebularNerd** [comment]
That's super basic, at a guess we could go with a very basic shim:

`import puremagic as imghdr`

Add a def for `.what` and just return the highest confidence extension minus the `.` from the database. That would provide a very basic drop-in replacment with the added power of the larger database. Folks could then transition to a proper PureMagic implementation.

**Comment by cdgriffith** [comment]
Released in https://github.com/cdgriffith/puremagic/releases/tag/1.24 thanks!
